### ISSUE TITLE
accepted Scope and Claim tracking

### ISSUE THREAD

**Issue by panva** [panva/node-oidc-provider#340]
Tracking progress here, discussion welcome.

- [x] it should be possible to return interaction results with less claims
  - something along the lines of interaction result object's `consent.rejectedClaims` property (`Array[String]`)
- [x] it should be possible to return interaction results with less scopes
  - something along the lines of interaction result object's `consent.rejectedScopes` property (`Array[String]`)
- [x] prompted scopes are tracked along side the client_id in the session
  - tracked in session object's `authorizations[client_id].promptedScopes` as an `Array[String]`
- [x] rejected scopes are tracked along side the client_id in the session
  - tracked in session object's `authorizations[client_id].rejectedScopes` as an `Array[String]`
- [x] prompted claims are tracked along side the client_id in the session
  - tracked in session object's `authorizations[client_id].promptedClaims` as an `Array[String]`
- [x] rejected claims are tracked along side the client_id in the session
  - tracked in session object's `authorizations[client_id].rejectedClaims` as an `Array[String]`
- [x] default interactionCheck should be checking the request scopes and request interaction whenever new ones are requested
- [x] default interactionCheck should be checking the request claims and request interaction whenever new ones are requested
- [x] prompted and rejected scopes, prompted and rejected claims, meta and sid are used in calculating the `session_state`
- [x] tokens and helper functions only get created/called with the accepted scopes and claims
- [x] system claims cannot be rejected
- [x] requesting the system scopes in addition does not result in an interaction (e.g. an added `max_age` parameter)
- [x] openid scope cannot be rejected
- [x] tests are passing
- [x] tests are added for the new functionality
- [x] documentation is updated

system claims are:
- sub
- sid
- auth_time
- acr
- amr
- iss

Resolves #339, #311

**Comment by P4sca1** [comment]
What is meant by non-system claims?

**Comment by panva** [comment]
> What is meant by non-system claims?

e.g. given_name, email. Essentially every other claim than the system ones mentioned above.

**Comment by panva** [comment]
revised the MVP

**Comment by sihunqu123** [comment]
Hi @panva, thanks for your quick reply. The suggestion of using interactionCheck is
really helpful, and I'am working on it now. For the 2nd suggestion,
_I didn’t want this cookie or session based._
does it mean we should NOT store scope value(that user agree to grant client) in ctx.oidc.session?

**Comment by panva** [comment]
I mean my preference would be that you track this somehow on your own if it should persist (for confidential clients) across sessions. My built-in solution that i’m working on will have this on the session anyway.

**Comment by panva** [comment]
progress in https://github.com/panva/node-oidc-provider/tree/feat/scope-claim-tracking

**Comment by sihunqu123** [comment]
Hi @panva, appreciate for your quick code action. Currently, **session based** is already enough for my case. Now I can see these code changes on branch scope-cliam-tracking, and that's what we really want.

**Comment by panva** [comment]
@sihunqu123 cool, but it'll take some time for me to ship, as-is it's not finished and i'm not happy with it to ship just yet.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/compare/master...feat/scope-claim-tracking

**Comment by panva** [comment]
✅ https://github.com/panva/node-oidc-provider/compare/master...feat/scope-claim-tracking

This is what i intend to ship. For those with explicitly provided `interactionCheck` this is 100% backwards compatible and you have to optin to use the new features to fix the "scope can be changed at will" issue unless it was already a part of your own (👍)

For those who use the implicit default `interactionCheck` helper (which i still don't recommend, even if you just take the default value and copy it to your codebase) this will be fixed.

For those with the default check relying on the broken behaviour, sorry - defaults are intended to be best current practice.

It currently works as described in the issue's description. The provider tracks separately prompted and rejected claims and scopes. By default, if a requested scope and/or claim was never prompted, it will be prompted for. If it was rejected it will simply be ignored and not returned.



With the feature in place you may add the following at the end of your `interactionCheck` function together with `extraParams: ['rerequest']` to get a facebook rerequest like behaviours.

<details>
  <summary>Click to expand</summary>

```js
if (ctx.oidc.params.rerequest !== undefined && !ctx.oidc.result) {
  const rejectedScopes = ctx.oidc.session.rejectedScopesFor(ctx.oidc.client.clientId);
  for (const scope of ctx.oidc.requestParamScopes) {
    if (rejectedScopes.has(scope)) {
      return {
        error: 'consent_required',
        error_description: 're-requested scopes not granted by End-User',
        reason: 're_request_scopes',
      };
    }
  }

  const rejectedClaims = ctx.oidc.session.rejectedClaimsFor(ctx.oidc.client.clientId);
  for (const claim of ctx.oidc.requestParamClaims) {
    if (rejectedClaims.has(claim)) {
      return {
        error: 'consent_required',
        error_description: 're-requested claims not granted by End-User',
        reason: 're_request_claims',
      };
    }
  }
}
```
</details>
